Add doc attributes to composite and attribute types
UAVCAN/pydsdl pull request #65
Opened 2021-03-31 05:09 UTC by bbworld1

This PR adds documentation support for #21. It exposes
comments on attributes and composite types (following proto convention
of having the comment come after the attribute) on a `doc: str` property
as described in https://forum.uavcan.org/t/generate-rich-navigable-html-docs-using-nunavut/1163.

2021-03-31 11:35 UTC, pavel-kirienko requested changes
This is a nice start but we need to address one architectural deficiency here: all objects created by the parser are intended to be [immutable](https://en.wikipedia.org/wiki/Immutable_object). Immutability pe se may appear to be of limited utility at this scope but on a larger scale, it helps ensure correctness and implement optimizations such as caching.

The problem specifically is the attribute `doc` being mutable. You may notice that all other attributes are not exposed directly but instead are [proxied via read-only properties](https://github.com/UAVCAN/pydsdl/blob/fadce78f69148ef9638da1c85f8e27b6e1018592/pydsdl/_serializable/_composite.py#L139-L252). We should follow the same approach for docs as well.

A possible way to implement it is to move your comment parsing logic from `DataSchemaBuilder.add_comment` directly into `_ParseTreeProcessor.visit_comment` such that you build up the comment string in there, and then pass it to [`StatementStreamProcessor.on_constant`](https://github.com/UAVCAN/pydsdl/blob/fadce78f69148ef9638da1c85f8e27b6e1018592/pydsdl/_parser.py#L56), `StatementStreamProcessor.on_field`, and `StatementStreamProcessor.on_padding_field` via an extra argument. I suppose you will also need to keep your new method `StatementStreamProcessor.on_comment` here but it will be used only for the top-level comment but not individual attribute comments.

2021-03-31 11:35 UTC, pavel-kirienko commented on pydsdl/_parser.py
> +        comment = node.text.lstrip("# ")
This breaks in cases like:

```
# This is my diagram:
#    #########
#    #  Box  #
#    #########
# This is an indented block:
#    Hello world!
```

We know from the [grammar definition](https://github.com/UAVCAN/pydsdl/blob/fadce78f69148ef9638da1c85f8e27b6e1018592/pydsdl/grammar.parsimonious#L3) that the first character is always `#`, so we could instead say this:

```suggestion
        comment = node.text[2:] if node.text.startswith("# ") else node.text[1:]
```

2021-04-02 18:49 UTC, pavel-kirienko requested changes
We are on the right track. Please see my suggestions.

2021-04-02 18:49 UTC, pavel-kirienko commented on pydsdl/_data_type_builder.py
> +        self._last_element_args = tuple()
This is okay but the amount of state is larger than necessary. Please collapse these into a single closure such that, for instance, instead of this:

```python
self._queue_attribute(
    self._structs[-1].add_constant,
    _serializable.Constant,
    constant_type, name, value
)
```

You go like:

```python
self._queue_attribute(
    lambda doc: self._structs[-1].add_constant(_serializable.Constant(constant_type, name, value, doc))
)
```

(if you view this as a special form of [CPS](https://en.wikipedia.org/wiki/Continuation-passing_style), it might be more correct to call this state "continuation", I suppose)

2021-04-02 18:49 UTC, pavel-kirienko commented on pydsdl/_data_type_builder.py
> +        self._flush_attribute()
This seems a tad fragile in the sense that there are multiple places in the builder that are responsible for managing the comments. You may notice that the parser (the `_ParseTreeProcessor`) is in the right context to detect reliably when the doc comment is finished (that is when it hits a line that is not comment-only). So what if instead of having a single abstract method `on_comment(comment, last_line_was_empty)` you had two methods:

```python
def on_comment_line(self, comment: str) -> None: ...
def on_comment_end(self) -> None: ...
```

This way you can delegate state management to the parser and simplify the builder greatly. Do you think it makes sense?

If you continue this line of thought, you may question why does the parser need to emit comments line-by-line. What if you build the comment in its entirety (multi-line) in the parser and then call the processor once?

```python
def on_doc_comment(self, comment_lines: str) -> None: ...
```

-----

Also, are you sure the current implementation will handle directives correctly? Like:

```
uint8 foo
# Much comment
# So detailed
@assert true
# How about this one?
```

2021-04-03 01:49 UTC, bbworld1 commented on pydsdl/_data_type_builder.py
> +        self._flush_attribute()
I agree that having the data type builder handle managing the comments in the way that it does right now is kind of fragile. I think I did it because I did not know how to flush remaining attributes through the parser upon reaching the file (which I have now realized is a dumb concern in multiple ways - first being that `visit_definition` is called on end of definition and thus can be used to do this, and second being that since each definition is required to end with either an @sealed or @extent directive it gets flushed anyway). 

I have re-implemented it as suggested, with the parser handling comment gathering.

2021-04-03 20:55 UTC, pavel-kirienko requested changes
Almost there! See my in-line comments.

2021-04-03 20:55 UTC, pavel-kirienko commented on pydsdl/_data_type_builder.py
> +            self._flush_attribute(comment)
I predict that this algorithm is going to break on a definition like https://github.com/UAVCAN/public_regulated_data_types/blob/53a7dbbf85554e11517c13ad91b9efb871599ad1/reg/drone/physics/kinematics/cartesian/PointVar.0.1.uavcan#L1-L2 because it doesn't have a header comment.

I should have mentioned it in the previous review but I failed to notice it: header and attribute comments are two distinct things and trying to manage both using the same interface leads to complications. Would you consider splitting the interface into two methods: `on_header_comment()` and `on_attribute_comment()` so that you don't need to rely on side effects like `self._structs[-1].doc == ""`? Again, the parser should be able to easily distinguish the two (e.g., anything you encounter before the first non-comment-only line is the header comment, anything after that are attribute comments).

2021-04-03 20:55 UTC, pavel-kirienko commented on pydsdl/_data_type_builder.py
> +        self._element_callback = None # type: typing.Callable
```suggestion
        self._element_callback = None # type: typing.Callable[[str], _serializable.Attribute]
```

2021-04-03 20:55 UTC, pavel-kirienko commented on pydsdl/_data_type_builder.py
> +            out = _serializable.DelimitedType(inner, extent=sm.extent, doc=builder.doc)  # type: _serializable.CompositeType
`DelimitedType` can take its `doc` from `inner.doc`, no need to pass the extra argument.

2021-04-03 20:55 UTC, pavel-kirienko commented on pydsdl/_parser.py
> +        self._comment = ""
You repeat these two lines a lot. Please extract them into a method.

2021-04-04 03:09 UTC, pavel-kirienko requested changes
Great. I have no further feedback regarding the business logic. Now we just need to add basic tests ensuring that the comments are extracted correctly and resolve the typing issues reported by MyPy. See the CI reports at https://ci.appveyor.com/project/Zubax/pydsdl

2021-04-04 12:01 UTC, pavel-kirienko approved these changes

2021-04-04 12:22 UTC, merged